language: objective-c
before_script:
    - brew update && brew upgrade xctool
xcode_project: TestFramework.xcodeproj
xcode_scheme: TestFramework
xcode_sdk: iphonesimulator

notifications:
  slack: inamiy:xBHDfhBnVMRYMKpl6AvJCJ1n